import { NextResponse } from "next/server";
import { NextRequest } from "next/server";
import { auth, clerkClient } from "@clerk/nextjs/server";
import { connectDB } from "@/lib/mongodb";
import { Invitation } from "@/lib/models/Invitation";
import { Project } from "@/lib/models/Project";
import type { IProjectMember } from "@/lib/models/Project";
import { pusherServer } from "@/lib/pusher";

export const runtime = "nodejs";

// GET /api/invitations — fetch all pending invitations for the logged-in user
export async function GET(_req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    // Get the user's email from Clerk — invitations are matched by email
    const client = await clerkClient();
    const clerkUser = await client.users.getUser(userId);
    const userEmail = clerkUser.emailAddresses[0]?.emailAddress;

    if (!userEmail) {
      return NextResponse.json(
        { message: "Could not determine user email" },
        { status: 400 }
      );
    }

    await connectDB();

    // Find all pending invitations sent to this user's email
    const invitations = await Invitation.find({
      recipient: userEmail,
      status: "pending",
    });

    return NextResponse.json(
      {
        success: true,
        data: invitations,
        message: "Invitations fetched successfully",
      },
      { status: 200 }
    );
  } catch (error: unknown) {
    console.error("[GET /api/invitations] error:", error);
    return NextResponse.json(
      { message: "Internal server error" },
      { status: 500 }
    );
  }
}

// POST /api/invitations — send an invitation to a user by email
export async function POST(req: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    // Parse and validate the request body
    const body = await req.json();
    const projectId: unknown = body.projectId;
    const recipientEmail: unknown = body.email; // we invite by EMAIL

    if (!projectId || typeof projectId !== "string") {
      return NextResponse.json(
        { message: "Project ID is required" },
        { status: 400 }
      );
    }

    if (!recipientEmail || typeof recipientEmail !== "string") {
      return NextResponse.json(
        { message: "Recipient email is required" },
        { status: 400 }
      );
    }

    await connectDB();

    // Only the project owner can send invitations
    const project = await Project.findOne({
      _id: projectId,
      "members.userId": userId,      // user must be in project
      owner: userId,                 // and must be the owner
    });

    if (!project) {
      return NextResponse.json(
        { message: "Project not found or you are not the owner" },
        { status: 404 }
      );
    }

    // Check if the email is already a member by looking up their Clerk account
    const client = await clerkClient();
    const existingUsers = await client.users.getUserList({
      emailAddress: [recipientEmail],
    });

    const recipientClerkUser = existingUsers.data[0];

    // If the person has an account, check if they're already a member
    if (recipientClerkUser) {
      const isAlreadyMember = project.members.some(
        (m: IProjectMember) => m.userId === recipientClerkUser.id
      );
      if (isAlreadyMember) {
        return NextResponse.json(
          { message: "This user is already a member of the project" },
          { status: 400 }
        );
      }
    }

    // Check if there's already a pending invitation to this email
    const existingInvite = await Invitation.findOne({
      project: projectId,
      recipient: recipientEmail,
      status: "pending",
    });

    if (existingInvite) {
      return NextResponse.json(
        { message: "An invitation has already been sent to this email" },
        { status: 400 }
      );
    }

    // Create the invitation — token is auto-generated by the model default
    const invite = await Invitation.create({
      project: projectId,
      inviter: userId,          // Clerk user ID of the sender
      recipient: recipientEmail, // email of the person being invited
    });

    // If the recipient already has an account, notify them in real-time
    if (recipientClerkUser) {
      await pusherServer.trigger(
        `private-user-${recipientClerkUser.id}`,
        "invitation:new",
        {}
      );
    }

    return NextResponse.json(
      { success: true, data: invite, message: "Invitation sent successfully" },
      { status: 201 }
    );
  } catch (error: unknown) {
    console.error("[POST /api/invitations] error:", error);
    return NextResponse.json(
      { message: "Internal server error" },
      { status: 500 }
    );
  }
}